# Generated by Django 4.2.5 on 2023-10-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DNI',
        ),
    ]
