# Generated by Django 4.2.5 on 2023-10-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_profile_dni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='DNI',
            new_name='DNI_USER',
        ),
    ]
