# Generated by Django 4.2.5 on 2023-10-03 16:09

from django.db import migrations, models
import erp.userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_rename_dni_profile_dni_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DNI_USER',
        ),
        migrations.AddField(
            model_name='profile',
            name='DNI',
            field=models.PositiveIntegerField(default=12345678, unique=True, validators=[erp.userauths.models.validate_dni_length]),
        ),
    ]
